### ISSUE TITLE
Custom mode opus file not clear playback gain

### ISSUE THREAD

**Issue by korongmambu** [complexlogic/loudgain#115]
Unlike easy mode, custom mode not clear header output / playback gain for opus file, either use opus-mode d, r, or s.

Edit: Sorry false report, this is only happen when use picard plugin. I thought this is custom mode bug since picard plugin use custom mode.

**Comment by complexlogic** [comment]
The reason is because the Picard plugin uses `rsgain` scans the files only. `rsgain` does not write to the files. Instead, it is Picard's responsibility to write to the files. Picard does not support setting the Opus header gain, so this feature is currently unsupported when using the Picard plugin.

**Comment by korongmambu** [comment]
Any plan for picard to implement this feature?
