### ISSUE TITLE
Missing distance space after error messages (before file fullpath)

### ISSUE THREAD

**Issue by pediRAM** [complexlogic/loudgain#121]
# Missing a space character at the end of the main error message string

Example error-messages from real world:
```
[ERROR] Could not open input: Invalid data found when processing inputography\2001 - Stiff Upper Lib (Tour Edition)\.@__thumb
[ERROR] Could not find audio stream c\Albums_Sorted\D\Drum 'n Base\mp3s_from_JZ\St. Germain
[ERROR] Could not open input: Invalidargumenttiert\_Groups\Rave\Hyper Hyper
```
This error messages were procued by: **rsgain-3.5.1-win64** ; running on **Win 11 Pro 23H2**

**Comment by complexlogic** [comment]
I'm guessing this is because the FFmpeg error buffer size was limited to 256 bytes, and the message is being truncated. Could you try the test build [here](https://github.com/complexlogic/rsgain/actions/runs/10021047885/artifacts/1721948393) and let me know if it fixes the problem? Use it on the same files if possible.

**Comment by pediRAM** [comment]
Hello @complexlogic. Thank you for your quick fix and feedback.
I've tested it by using following parameters ```rsgain.exe easy -l -16 -m 4 D:\ILAMI```.
This was the result:
```
[ERROR] Could not open input: Invalid data found when processing input
[ERROR] Could not find audio streamI\Sima Bina
[ERROR] Could not find audio streamI\Siavash ghomeyshi
[ERROR] Could not find audio streamop_Hits_90s\Die Prinzen
[ERROR] Could not open input: Invalid argument_90s\Enya
[ERROR] Could not open input: Invalid argument_90s\Gospels
```

**Comment by complexlogic** [comment]
The root cause of this issue is the method that is used to output to the screen during the multithreading mode. The multithreading progress messages don't create a newline, using a carriage return instead. This causes error messages to overlap on top of the normal progress messages, which creates the formatting issue you reported above. So, I'm just going to disable the error messages while a multithreading scan is in progress. Users will still have the end-of-scan error reports.

Thanks for your help on this one.
