### ISSUE TITLE
no run with certain arguments

### ISSUE THREAD

**Issue by Dogway** [complexlogic/loudgain#37]
Executing the following:
```
for %%F in ("%FOLDER%\*.mp3") do (
    rsgain custom -t -I 4 -L -s i -c p -l -18 "%%F"
)
```
Won't run in Win7 x64 until I remove `-t` (true peak) and lower tag version to 3 (`-I 3`).
Also `-s` doesn't accept `e` anymore

Old version (2.0.1) works fine:
```
for %%F in ("%FOLDER%\*.mp3") do (
    rsgain custom -r -k -K -2.0 -s e -d 0.0 -L -S -I 4 "%%F"
)
```

**Comment by complexlogic** [comment]
Can you post the output? There should be an error message.

**Comment by Dogway** [comment]
No sorry, silent _"crash"_. Is there any verbose mode?

**Comment by complexlogic** [comment]
I was able to reproduce this. There is a problem with the ID3v2 version parsing. I fixed it. Could you try out the new build [here](https://github.com/complexlogic/rsgain/suites/9215527664/artifacts/430286650) and let me know if it fixes for you?

The `-s e` mode was removed because it enabled non-standard tags.

**Comment by Dogway** [comment]
Yes, working great now, I compared both versions and they match Gain and Peak. The only thing it doesn't write RefLoud nor Range. I think they were useful though, specially RefLoud.

EDIT: By the way, an option to keep timestamps would be great.
