### ISSUE TITLE
A problem about redirecting output of rsgain

### ISSUE THREAD

**Issue by ZXfkSIE** [complexlogic/loudgain#4]
First of all, thank you for bringing wonderful `loudgain` to Windows. I have downloaded version `2.0.1` it from the release page.
I am trying to save output result of `rsgain` to a `.txt` file, but I could not manage to do it.
I run
```
C:/rsgain-2.0.1-win64/rsgain.exe -v 1>out.txt 2>err.txt
```
for example. However, the result is still output to the Windows PowerShell window, and both `out.txt` and `err.txt` remain empty.
Could you please tell me that is there something wrong with my command line, or how to solve this problem.
I guess this post https://stackoverflow.com/questions/41556226/windows-console-output-not-going-to-stdout-nor-stderr may be related.
Thank you very much.

**Comment by complexlogic** [comment]
The reason is because rsgain uses the WIN32 function [WriteConsole](https://docs.microsoft.com/en-us/windows/console/writeconsole) for output instead of C's stdio (printf, fprintf, etc.), so the outputted text is not sent to `stdout` and `stderr`. However, for the tab-delimited output (for .csv spreadsheet), I made sure to still use `stdout`, so that function still works.

The reason I chose `WriteConsole` is because of some I/O performance issues I was encountering when I ported loudgain to Windows. I just made an experimental change in the code to use `stdio` for output and it works just as well, so this concern now appears to be unfounded. I uploaded the experimental build [here](https://github.com/complexlogic/rsgain/files/9375310/rsgain-2.0.1-win64-modified.zip). You can download it and verify that redirecting `stdout` and `stderr` now works successfully.

However, the main output from `loudgain` and `rsgain` is not really meant to be viewed in a plain text format. The text editor doesn't decode the console color codes, and each progress bar update shows on individual lines which bloats the file with unnecessary information. This is why it is only recommended to redirect output only when using the `-O` option, since the program will make sure to output the information in a readable format.

**Comment by ZXfkSIE** [comment]
Thank you for your detailed response. Actually I am implementing ReplayGain scanning function of https://github.com/ZXfkSIE/ThousandPlayer based on calling your work externally, and it needs to check whether that exe file set by the user is rsgain's main program. I've gave up reading the output result from `rsgain -v` since I could not find a way to retrieve the strings output by `WriteConsole`.
There is another way to check whether the program is done by you: read the "Product name" item through `GetFileVersionInfoA` and `VerQueryValueA`. However, the `2.0.1` main program does not contain any `VERSIONINFO` tags.
Well the main program does integrate a manifest file which contains `name` and `version`, but extracting and reading that will be much more complicated. Besides, I think integrating `VERSIONINFO` to your main exe will make your project much more normative.

**Comment by complexlogic** [comment]
Ok. I am working on rsgain version 3.0 currently, which is a major update that has not been released yet. It will be at least a few more weeks before it is ready for release.

I added a resource file to the project which includes `VERSIONINFO`  using the CMake variables. You can download the latest rsgain 3.0 build [here](https://github.com/complexlogic/rsgain/files/9379185/rsgain-3.0-win64.zip). Here is the generated resource file which `rsgain.exe` was compiled with:
```
VS_VERSION_INFO VERSIONINFO
    FILEVERSION    3,0,0,0
    PRODUCTVERSION 3,0,0,0
{
    BLOCK "StringFileInfo"
    {
        BLOCK "040904b0"
        {
            VALUE "CompanyName",        "complexlogic"
            VALUE "FileDescription",    "ReplayGain 2.0 loudness normalizer"
            VALUE "FileVersion",        "3.0"
            VALUE "OriginalFilename",   "rsgain.exe"
            VALUE "ProductName",        "rsgain"
            VALUE "ProductVersion",     "3.0"
        }
    }
    BLOCK "VarFileInfo"
    {
        VALUE "Translation", 0x409, 1200
    }
}
```

You should now be able to query this information via the WIN32 API to verify the authenticity of the file.

**Comment by ZXfkSIE** [comment]
Thank you very much. Looking forward to your 3.0 release.
