### ISSUE TITLE
add an option to put the separator in the beginning of every csv file

### ISSUE THREAD

**Issue by peterseter** [complexlogic/loudgain#56]
add an option in easy mode so that when you do -O, the files will start with the following first line
sep=	
(there is a horizontal tabulation there after the =)

otherwise the csv files just refuse to split into columns for me. I have tried everything else.

**Comment by complexlogic** [comment]
Which platform are you on and which application are you using to open the CSV files?

**Comment by peterseter** [comment]
I am on windows 10, using Microsoft excel to open the files. I'd like to keep Microsoft excel as the default program to open csv files. I tried to google for solutions but none of them worked for me. and well, if adding this feature is not possible I can just temporarily switch to another program whenever opening these files, it's okay. it would just be a mild convenience to have this option.

**Comment by complexlogic** [comment]
Ok. I had no idea this was an issue for Microsoft Excel.

I did a bit of searching and I understand how it works. This would be relatively trivial to add. Since it's non-standard, it will have to be an option. I can make the `-O` switch take an optional argument, so for example you would use `-Os` instead of `-O` to have the separator header. Implementing via optional argument would preserve the existing tag output format for others that depend on it such as the MusicBrainz Picard plugin.

**Comment by complexlogic** [comment]
I'm not planning on doing another release for a while. If you want to use this feature now you can download the git `master` build [here](https://github.com/complexlogic/rsgain/suites/11622548729/artifacts/603007819).
