### ISSUE TITLE
Compile from source on Windows doesn't work

### ISSUE THREAD

**Issue by TomKranenburg** [complexlogic/loudgain#57]
So it compiles successfully it seems, but when running the program I'm hit with a fmt.dll not found.

Any ideas?

**Comment by complexlogic** [comment]
In `<build_dir>\Release`, do you see the `fmt.dll` in there?

**Comment by TomKranenburg** [comment]
I don't actually see a Release folder in there. There is a Debug folder containing the binary but that's it.

**Comment by complexlogic** [comment]
You're right, that's because the Debug release type is chosen by default.

The Windows build instructions were outdated; I changed the project to use static builds for Windows about 6 months ago, but didn't update the build instructions accordingly. 

I just updated the build instructions to use the static linking, so you won't need to worry about missing DLLs anymore. Delete everything in your build folder then start over from the beginning. If you're still experiencing issues, please let me know and I can re-open the issue.

**Comment by TomKranenburg** [comment]
Thanks for this. I want to try contribute to your codebase a little as it's really great. So getting it to compile is the first step.

I'm sure this will work, but if it doesn't I'll reopen.

**Comment by TomKranenburg** [comment]
Sadly I'm still getting the same error here.

**Comment by complexlogic** [comment]
Did you delete your `build` directory and start over from the beginning? It shouldn't be searching for any DLLs at startup.

**Comment by TomKranenburg** [comment]
I did indeed. Wiped everything and cloned the git again. I'm using the installation tools provided with Visual Studio 2022. I did try VS 2019 just in case. Both are the latest version.

**Comment by complexlogic** [comment]
I just realized I had a typo in the CMake generation command. Also, I think there may be a linking issue with the Debug libraries, so I switched the build type to Release.

I updated the instructions again. Please delete everything and try one more time.

**Comment by TomKranenburg** [comment]
Ok this has worked (:

Thank you, I'll now attempt to contribute to the codebase anyway I can.
