### ISSUE TITLE
Wrong gain on opus files

### ISSUE THREAD

**Issue by emperor06** [complexlogic/loudgain#65]
When applying a given loudness to the same song in multiple formats, the opus files are noticeably louder than the rest.

For example, I start with 2 songs (another.wav and teset.wav), encode them in mp3, aac, and opus, then apply replaygain with:
```
$ rsgain custom -s i -l -14 -c n -o r -a -O *
Filename        Loudness (LUFS) Gain (dB)       Peak     Peak (dB)      Peak Type       Clipping Adjustment?
another.m4a     -7.22   -6.78   1.000000        0.00    Sample  N
another.mp3     -7.11   -6.89   1.000000        0.00    Sample  N
another.opus    -7.10   -6.90   1.000000        0.00    Sample  N
another.wav     -7.14   -6.86   0.999817        -0.00   Sample  N
teset.m4a       -14.12  0.12    0.989655        -0.09   Sample  N
teset.mp3       -13.99  -0.01   1.000000        0.00    Sample  N
teset.opus      -14.10  0.10    0.993439        -0.06   Sample  N
teset.wav       -14.03  0.03    0.999908        -0.00   Sample  N
Album   -9.19   -4.81   1.000000        0.00    Sample  N
```

Foobar2000 tells me another.m4a has a track gain of -6.78dB and an album gain of -4.81dB, which matches rsgain's output. But for another.opus, track gain is -1.90dB and album gain is +0.19dB.

Same goes with teset.opus which has gains of +5.10dB and +0.19dB.

Now, maybe that's a problem with how Foobar reads the header, I don't know. Rsgain and Foobar seem to handle the ogg header very differently.

**Comment by emperor06** [comment]
It seems like Foobar always adds 5dB to opus tracks that have a r128_track_gain, so I made a profile that has a general target loudness of -14 LUFS and opus target loudness of -19 LUFS. Now all my albums play at the same perceived volume.

**Comment by complexlogic** [comment]
rsgain normalizes all audio to -18 LUFS unless otherwise specified. RFC 7845 calls for the `R128_TRACK_GAIN` and `R128_ALBUM_GAIN` tags to be referenced to -23 LUFS. Some players will automatically add 5 dB to the gain to attempt to compensate for the loudness difference between the normalization schemes. You will need to learn how the player(s) that you use handle Opus files and adjust your rsgain settings accordingly.

I wrote about the complexity of the Opus situation [here](https://github.com/complexlogic/rsgain#opus-files). I recommend giving that a read.
