### ISSUE TITLE
Symbol lookup error: undefined symbol

### ISSUE THREAD

**Issue by helkaluin** [complexlogic/loudgain#80]
I'm running this through my whole library, and rsgain crashes with:

`rsgain: symbol lookup error: rsgain: undefined symbol: _ZN6TagLib4MPEG4File4saveEiNS_4File9StripTagsENS_5ID3v27VersionENS2_13DuplicateTagsE`

Do let me know how can I generate more verbose logs to help debugging this. As it stands I don't even know which file triggered it.

**Comment by complexlogic** [comment]
This is a linking issue with TagLib. Please let me know how you installed rsgain, and which distro + version you are running.

**Comment by helkaluin** [comment]
Sure thing. This is running on Ubuntu 23.04, installed rsgain with the .deb provided with the v3.4 release. TagLib is at 1.11.1 in the repos.

**Comment by complexlogic** [comment]
Well that explains it then. The .deb package was built against TagLib 1.13, a newer version of TagLib, and the missing symbol doesn't exist in 1.11.1. I had assumed that Debian and Ubuntu were on the same TagLib version, but it is apparently not the case. I'll rebuild the package with a statically-linked TagLib so that it works on both Debian and Ubuntu.

In the meantime, you can [build from source](https://github.com/complexlogic/rsgain/blob/master/docs/BUILDING.md) as a workaround until I get around to rebuilding the package.

**Comment by helkaluin** [comment]
Many thanks!
