### ISSUE TITLE
v3.0 not installable in ubuntu 22.04

### ISSUE THREAD

**Issue by pdfrg** [complexlogic/loudgain#9]
apt error message:

Depends: libfmt7 but it is not installable

Installed libfmt8, but still won't install.

Thanks, looking forward to trying.

**Comment by complexlogic** [comment]
Thanks for the report. I try to build the package so that it will be compatible with both Debian and Ubuntu. In this case, it appears that there is an unresolvable conflict due to the `fmt` versions between the two distros. I solved it by statically linking version 8.1.1 instead of using the distro-provided `fmt`.  

The package on the release page has been replaced. Could you please try again and let me know if it works for you?

**Comment by pdfrg** [comment]
Updated .deb installs now!
Thank you so much for the fast response.

apt throws the following error
N: Download is performed unsandboxed as root as file '/home/USER/rsgain_3.0_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

But I can still run rsgain.

Thanks again!

**Comment by complexlogic** [comment]
Glad it's working now. The `N:...` is a notice, not an error, so I'm going to consider this resolved.
