### ISSUE TITLE
ReplayGain 2.0 for Opus Files

### ISSUE THREAD

**Issue by codenamek83** [complexlogic/loudgain#97]
First and foremost, thank you for your dedication to building and maintaining this application. I am currently in the process of transitioning from MP3 to the Opus file format, with about 10% of my files still in MP3 and M4A formats.

Regarding ReplayGain, I prefer to stick with the 2.0 standard. 'Rsgain' has successfully tagged the Opus files with 2.0 tags, and I am not experiencing any issues with playback. Both the web player and desktop player can detect the ReplayGain tags and apply them accordingly.

I would like to seek clarification on whether sticking with the ReplayGain 2.0 standard could cause any issues now or in the near future. In your documentation, you mentioned, 'If you wish to write tags that are fully compliant to RFC 7845 instead of ReplayGain 2.0, you can use the -o 's' option.' Is this compliance merely for documentation purposes, or are there potential technical issues I might encounter?

**Comment by complexlogic** [comment]
> Is this compliance merely for documentation purposes, or are there potential technical issues I might encounter

The challenge with the Opus format is that ReplayGain implementations vary depending on the player:
- Some players read `REPLAYGAIN` tags only
- Some players read `R128` tags only
- Some players read both

Most scanners only write one tag or the other. That's why I designed rsgain to be configurable for Opus files, so that it supports both standards and allows the user to pick which one to use.

Ultimately it's the user's responsibility to research how their chosen player(s) handle loudness normalization for the Opus format, and adjust their rsgain settings accordingly. rsgain only alters the file's metadata, i.e. the changes are completely reversible. So, if in the future you want to change which standard you use, you can re-scan the files with new settings and the operation will be completely lossless.
